common: &common
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: recsolu430

development:
  <<: *common
  database: static_pages_development

staging:
  <<: *common
  database: static_pagees_staging

test: &test
  <<: *common
  database: static_pages_test

production:
  <<: *common
  database: statoc_pages_production
