common: &common
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: briansarsany
  password:
  host: 127.0.0.1

development:
  <<: *common
  database: static_pages_development

staging:
  <<: *common
  database: static_pagees_staging

test: &test
  <<: *common
  database: static_pages_test

production:
  <<: *common
  database: statoc_pages_production
